# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'velocity_window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VelocityWindow(object):
    def setupUi(self, VelocityWindow):
        VelocityWindow.setObjectName("VelocityWindow")
        VelocityWindow.resize(1014, 679)
        self.hbox_VelocityWindow = QtWidgets.QHBoxLayout(VelocityWindow)
        self.hbox_VelocityWindow.setObjectName("hbox_VelocityWindow")
        self.grid_settings = QtWidgets.QGridLayout()
        self.grid_settings.setHorizontalSpacing(6)
        self.grid_settings.setObjectName("grid_settings")
        self.combo_box_select_gas = QtWidgets.QComboBox(VelocityWindow)
        self.combo_box_select_gas.setMinimumContentsLength(0)
        self.combo_box_select_gas.setObjectName("combo_box_select_gas")
        self.combo_box_select_gas.addItem("")
        self.combo_box_select_gas.addItem("")
        self.combo_box_select_gas.addItem("")
        self.combo_box_select_gas.addItem("")
        self.combo_box_select_gas.addItem("")
        self.combo_box_select_gas.addItem("")
        self.combo_box_select_gas.addItem("")
        self.grid_settings.addWidget(self.combo_box_select_gas, 0, 1, 1, 1)
        self.label_select_temp = QtWidgets.QLabel(VelocityWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_temp.setFont(font)
        self.label_select_temp.setObjectName("label_select_temp")
        self.grid_settings.addWidget(self.label_select_temp, 1, 0, 1, 1)
        self.hbox_input_temp = QtWidgets.QHBoxLayout()
        self.hbox_input_temp.setObjectName("hbox_input_temp")
        self.input_temp = QtWidgets.QLineEdit(VelocityWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_temp.sizePolicy().hasHeightForWidth())
        self.input_temp.setSizePolicy(sizePolicy)
        self.input_temp.setObjectName("input_temp")
        self.hbox_input_temp.addWidget(self.input_temp)
        self.label_input_temp = QtWidgets.QLabel(VelocityWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_input_temp.sizePolicy().hasHeightForWidth())
        self.label_input_temp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_temp.setFont(font)
        self.label_input_temp.setObjectName("label_input_temp")
        self.hbox_input_temp.addWidget(self.label_input_temp)
        self.grid_settings.addLayout(self.hbox_input_temp, 1, 1, 1, 1)
        self.label_select_press = QtWidgets.QLabel(VelocityWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_press.setFont(font)
        self.label_select_press.setObjectName("label_select_press")
        self.grid_settings.addWidget(self.label_select_press, 2, 0, 1, 1)
        self.hbox_input_press = QtWidgets.QHBoxLayout()
        self.hbox_input_press.setObjectName("hbox_input_press")
        self.input_press = QtWidgets.QLineEdit(VelocityWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_press.sizePolicy().hasHeightForWidth())
        self.input_press.setSizePolicy(sizePolicy)
        self.input_press.setObjectName("input_press")
        self.hbox_input_press.addWidget(self.input_press)
        self.label_input_press = QtWidgets.QLabel(VelocityWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_input_press.sizePolicy().hasHeightForWidth())
        self.label_input_press.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_press.setFont(font)
        self.label_input_press.setObjectName("label_input_press")
        self.hbox_input_press.addWidget(self.label_input_press)
        self.grid_settings.addLayout(self.hbox_input_press, 2, 1, 1, 1)
        self.label_select_type_of_data = QtWidgets.QLabel(VelocityWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_type_of_data.setFont(font)
        self.label_select_type_of_data.setObjectName("label_select_type_of_data")
        self.grid_settings.addWidget(self.label_select_type_of_data, 3, 0, 1, 1)
        self.select_data_type = QtWidgets.QTabWidget(VelocityWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_data_type.sizePolicy().hasHeightForWidth())
        self.select_data_type.setSizePolicy(sizePolicy)
        self.select_data_type.setObjectName("select_data_type")
        self.tab_isobaric = QtWidgets.QWidget()
        self.tab_isobaric.setObjectName("tab_isobaric")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_isobaric)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vbox_select_isobaric = QtWidgets.QVBoxLayout()
        self.vbox_select_isobaric.setObjectName("vbox_select_isobaric")
        self.radio_select_data_type_isobaric = QtWidgets.QRadioButton(self.tab_isobaric)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radio_select_data_type_isobaric.setFont(font)
        self.radio_select_data_type_isobaric.setAutoExclusive(True)
        self.radio_select_data_type_isobaric.setObjectName("radio_select_data_type_isobaric")
        self.data_type_selection = QtWidgets.QButtonGroup(VelocityWindow)
        self.data_type_selection.setObjectName("data_type_selection")
        self.data_type_selection.addButton(self.radio_select_data_type_isobaric)
        self.vbox_select_isobaric.addWidget(self.radio_select_data_type_isobaric)
        self.grid_select_isobaric = QtWidgets.QGridLayout()
        self.grid_select_isobaric.setObjectName("grid_select_isobaric")
        self.input_t_low = QtWidgets.QLineEdit(self.tab_isobaric)
        self.input_t_low.setObjectName("input_t_low")
        self.grid_select_isobaric.addWidget(self.input_t_low, 0, 1, 1, 1)
        self.label_input_t_low = QtWidgets.QLabel(self.tab_isobaric)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_t_low.setFont(font)
        self.label_input_t_low.setObjectName("label_input_t_low")
        self.grid_select_isobaric.addWidget(self.label_input_t_low, 0, 2, 1, 1)
        self.label_select_t_low = QtWidgets.QLabel(self.tab_isobaric)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_t_low.setFont(font)
        self.label_select_t_low.setObjectName("label_select_t_low")
        self.grid_select_isobaric.addWidget(self.label_select_t_low, 0, 0, 1, 1)
        self.label_select_t_high = QtWidgets.QLabel(self.tab_isobaric)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_t_high.setFont(font)
        self.label_select_t_high.setObjectName("label_select_t_high")
        self.grid_select_isobaric.addWidget(self.label_select_t_high, 1, 0, 1, 1)
        self.label_input_t_high = QtWidgets.QLabel(self.tab_isobaric)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_t_high.setFont(font)
        self.label_input_t_high.setObjectName("label_input_t_high")
        self.grid_select_isobaric.addWidget(self.label_input_t_high, 1, 2, 1, 1)
        self.input_t_high = QtWidgets.QLineEdit(self.tab_isobaric)
        self.input_t_high.setObjectName("input_t_high")
        self.grid_select_isobaric.addWidget(self.input_t_high, 1, 1, 1, 1)
        self.vbox_select_isobaric.addLayout(self.grid_select_isobaric)
        self.verticalLayout_2.addLayout(self.vbox_select_isobaric)
        self.select_data_type.addTab(self.tab_isobaric, "")
        self.tab_isothermal = QtWidgets.QWidget()
        self.tab_isothermal.setObjectName("tab_isothermal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_isothermal)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vbox_select_isothermal = QtWidgets.QVBoxLayout()
        self.vbox_select_isothermal.setObjectName("vbox_select_isothermal")
        self.radio_select_data_type_isothermal = QtWidgets.QRadioButton(self.tab_isothermal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radio_select_data_type_isothermal.setFont(font)
        self.radio_select_data_type_isothermal.setObjectName("radio_select_data_type_isothermal")
        self.data_type_selection.addButton(self.radio_select_data_type_isothermal)
        self.vbox_select_isothermal.addWidget(self.radio_select_data_type_isothermal)
        self.grid_select_isothermal = QtWidgets.QGridLayout()
        self.grid_select_isothermal.setObjectName("grid_select_isothermal")
        self.label_select_p_low = QtWidgets.QLabel(self.tab_isothermal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_p_low.setFont(font)
        self.label_select_p_low.setObjectName("label_select_p_low")
        self.grid_select_isothermal.addWidget(self.label_select_p_low, 0, 0, 1, 1)
        self.input_p_low = QtWidgets.QLineEdit(self.tab_isothermal)
        self.input_p_low.setObjectName("input_p_low")
        self.grid_select_isothermal.addWidget(self.input_p_low, 0, 1, 1, 1)
        self.label_input_p_low = QtWidgets.QLabel(self.tab_isothermal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_p_low.setFont(font)
        self.label_input_p_low.setObjectName("label_input_p_low")
        self.grid_select_isothermal.addWidget(self.label_input_p_low, 0, 2, 1, 1)
        self.label_select_p_high = QtWidgets.QLabel(self.tab_isothermal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_p_high.setFont(font)
        self.label_select_p_high.setObjectName("label_select_p_high")
        self.grid_select_isothermal.addWidget(self.label_select_p_high, 1, 0, 1, 1)
        self.input_p_high = QtWidgets.QLineEdit(self.tab_isothermal)
        self.input_p_high.setObjectName("input_p_high")
        self.grid_select_isothermal.addWidget(self.input_p_high, 1, 1, 1, 1)
        self.label_input_p_high = QtWidgets.QLabel(self.tab_isothermal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_p_high.setFont(font)
        self.label_input_p_high.setObjectName("label_input_p_high")
        self.grid_select_isothermal.addWidget(self.label_input_p_high, 1, 2, 1, 1)
        self.vbox_select_isothermal.addLayout(self.grid_select_isothermal)
        self.verticalLayout_4.addLayout(self.vbox_select_isothermal)
        self.select_data_type.addTab(self.tab_isothermal, "")
        self.grid_settings.addWidget(self.select_data_type, 3, 1, 1, 1)
        self.label_select_gas = QtWidgets.QLabel(VelocityWindow)
        self.label_select_gas.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_select_gas.sizePolicy().hasHeightForWidth())
        self.label_select_gas.setSizePolicy(sizePolicy)
        self.label_select_gas.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_gas.setFont(font)
        self.label_select_gas.setObjectName("label_select_gas")
        self.grid_settings.addWidget(self.label_select_gas, 0, 0, 1, 1)
        self.button_calculate = QtWidgets.QPushButton(VelocityWindow)
        self.button_calculate.setObjectName("button_calculate")
        self.grid_settings.addWidget(self.button_calculate, 4, 1, 1, 1)
        self.hbox_VelocityWindow.addLayout(self.grid_settings)
        self.mpl_widget = MatplotlibWidget(VelocityWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget.sizePolicy().hasHeightForWidth())
        self.mpl_widget.setSizePolicy(sizePolicy)
        self.mpl_widget.setMinimumSize(QtCore.QSize(400, 400))
        self.mpl_widget.setObjectName("mpl_widget")
        self.hbox_VelocityWindow.addWidget(self.mpl_widget)

        self.retranslateUi(VelocityWindow)
        self.combo_box_select_gas.setCurrentIndex(0)
        self.select_data_type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VelocityWindow)

    def retranslateUi(self, VelocityWindow):
        _translate = QtCore.QCoreApplication.translate
        VelocityWindow.setWindowTitle(_translate("VelocityWindow", "Velocity Calculator"))
        self.combo_box_select_gas.setItemText(0, _translate("VelocityWindow", "Hydrogen"))
        self.combo_box_select_gas.setItemText(1, _translate("VelocityWindow", "Nitrogen"))
        self.combo_box_select_gas.setItemText(2, _translate("VelocityWindow", "Helium"))
        self.combo_box_select_gas.setItemText(3, _translate("VelocityWindow", "Neon"))
        self.combo_box_select_gas.setItemText(4, _translate("VelocityWindow", "Argon"))
        self.combo_box_select_gas.setItemText(5, _translate("VelocityWindow", "Krypton"))
        self.combo_box_select_gas.setItemText(6, _translate("VelocityWindow", "Xenon"))
        self.label_select_temp.setText(_translate("VelocityWindow", "Select source temperature:"))
        self.label_input_temp.setText(_translate("VelocityWindow", "Kelvin"))
        self.label_select_press.setText(_translate("VelocityWindow", "Select source pressure:"))
        self.label_input_press.setText(_translate("VelocityWindow", "bar"))
        self.label_select_type_of_data.setText(_translate("VelocityWindow", "Select type of data:"))
        self.radio_select_data_type_isobaric.setText(_translate("VelocityWindow", "Select"))
        self.label_input_t_low.setText(_translate("VelocityWindow", "Kelvin"))
        self.label_select_t_low.setText(_translate("VelocityWindow", "Select minimum temperature value:"))
        self.label_select_t_high.setText(_translate("VelocityWindow", "Select maximum temperature value:"))
        self.label_input_t_high.setText(_translate("VelocityWindow", "Kelvin"))
        self.select_data_type.setTabText(self.select_data_type.indexOf(self.tab_isobaric), _translate("VelocityWindow", "Isobaric"))
        self.radio_select_data_type_isothermal.setText(_translate("VelocityWindow", "Select"))
        self.label_select_p_low.setText(_translate("VelocityWindow", "Select minimum pressure value:"))
        self.label_input_p_low.setText(_translate("VelocityWindow", "bar"))
        self.label_select_p_high.setText(_translate("VelocityWindow", "Select maximum pressure value:"))
        self.label_input_p_high.setText(_translate("VelocityWindow", "bar"))
        self.select_data_type.setTabText(self.select_data_type.indexOf(self.tab_isothermal), _translate("VelocityWindow", "Isothermal"))
        self.label_select_gas.setText(_translate("VelocityWindow", "Select gas species:"))
        self.button_calculate.setText(_translate("VelocityWindow", "Calculate !"))

from matplotlibwidget import MatplotlibWidget
